### ISSUE TITLE
[Feature] Possible addition of the repository and service pattern

### ISSUE THREAD

**Issue by Caixetadev** [kevinanielsen/go-fast-cdn#101]
**Is your feature request related to a problem? Please describe.** <br>
handlers are coupled with the database and business rules

**Describe the solution you'd like**<br>
implement the patterns

[service](https://www.alexedwards.net/blog/the-fat-service-pattern)
[repository](https://threedots.tech/post/repository-pattern-in-go/)

**Describe alternatives you've considered**<br>

**Additional context**<br>

**Comment by kevinanielsen** [comment]
I like this a lot - Would you like to work on this?

**Comment by Caixetadev** [comment]
Yes

**Comment by anveshthakur** [comment]
Hi, I was going through this issue and made a the necessary changes related for implementing the repository pattern for this you can check it over here. [#141](https://github.com/kevinanielsen/go-fast-cdn/pull/141)
