### ISSUE TITLE
[Feature]  Refactor the project folder system to the golang way

### ISSUE THREAD

**Issue by Caixetadev** [kevinanielsen/go-fast-cdn#114]
**Is your feature request related to a problem? Please describe.** <br>
Yes, golang developers are already used to a folder architecture, if we follow this architecture we can make it easier for potential contributors in the future

**Describe the solution you'd like**<br>
implement golang [project-layout](https://github.com/golang-standards/project-layout)

**Describe alternatives you've considered**<br>

**Additional context**<br>

**Comment by kevinanielsen** [comment]
This would be great - Do you want to be assigned to this?

**Comment by Caixetadev** [comment]
yes
