### ISSUE TITLE
[Feature] Upload document type ZIP

### ISSUE THREAD

**Issue by Logikoz** [kevinanielsen/go-fast-cdn#139]
**Is your feature request related to a problem? Please describe.** <br>
support to application/zip

**Comment by kevinanielsen** [comment]
Would you like to work on this?

**Comment by unamdev0** [comment]
Hey @kevinanielsen , can I work on this feature?

**Comment by Logikoz** [comment]
@unamdev0 you must! :D

**Comment by Logikoz** [comment]
fork this repo, and implements the new features...

on finish, create pull request...

**Comment by Logikoz** [comment]
I can't, because I don't understand Go Lang.

**Comment by unamdev0** [comment]
@Logikoz  thanks buddy :)  I'm new to golang as well, but this seemed like a small change with which I can start contributing to open source.

Here's the PR- 
https://github.com/kevinanielsen/go-fast-cdn/pull/140

**Comment by kevinanielsen** [comment]
@unamdev0 Thanks for the contribution
@Logikoz Thank you for hyping up unamdev0 ;)
