### ISSUE TITLE
[Feature] Add API endpoint for renaming files

### ISSUE THREAD

**Issue by kevinanielsen** [kevinanielsen/go-fast-cdn#18]

**Comment by webstradev** [comment]
I can take a crack at this

**Comment by kevinanielsen** [comment]
Would be great! Assigning you now

**Comment by webstradev** [comment]
Just wondering, have you thought at all about how you wanna structure the api router and how you wanna get the filename input. The two open issues now don't reaally fit on either of the two api subgroups.
Maybe one for file
which would have a file.PUT("/:id") and a file.DELETE("/:id")
