### ISSUE TITLE
[Feature] Add API endpoint for deleting files

### ISSUE THREAD

**Issue by kevinanielsen** [kevinanielsen/go-fast-cdn#19]

**Comment by ankit-pn** [comment]
I want to work on this issue, it would be great if you assign this to me

**Comment by kevinanielsen** [comment]
@ankit-pn You have been assigned. Make sure to check out the [documentation about contributing](https://kevinanielsen.github.io/go-fast-cdn/contribution/development/).

**Comment by ankit-pn** [comment]
I have restructured data package and pushed the change for delete api. I have tested the API on my local machine and it is working good. Included in on  #28
