### ISSUE TITLE
[Testing] Write test for FilterFilename function

### ISSUE THREAD

**Issue by kevinanielsen** [kevinanielsen/go-fast-cdn#49]
The FilterFilename function for filtering out periods, slashes, and backslashes has no tests written for it.

**Comment by ankit-pn** [comment]
Hey I want to work on this issue, i would be great if you assign this to me!

**Comment by kevinanielsen** [comment]
Sounds good! Assigning you now :)

**Comment by raj3k** [comment]
Hey, i've added tests for FilterFilename function in [#52](https://github.com/kevinanielsen/go-fast-cdn/pull/52)

**Comment by kevinanielsen** [comment]
@raj3k I just noticed - I am closing this issue. 

@ankit-pn - Let me know if you want to work on another issue!
