### ISSUE TITLE
[Feature] Make upload file button clear the file input

### ISSUE THREAD

**Issue by kevinanielsen** [kevinanielsen/go-fast-cdn#50]
**Is your feature request related to a problem? Please describe.**
When a file is successfully uploaded, the file input is not cleared and the old file persists.

**Describe the solution you'd like**
When the file is uploaded **successfully** the file input should be cleared.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by GDThumar2409** [comment]
if no one is working on this i am thinking start to working on this.

**Comment by kevinanielsen** [comment]
@GDThumar2409 That would be great - assigning you now :)
