### ISSUE TITLE
[Feature] Add handler for resizing images

### ISSUE THREAD

**Issue by kevinanielsen** [kevinanielsen/go-fast-cdn#58]
**Is your feature request related to a problem? Please describe.** <br>
Currently, no way to resize images when uploading

**Describe the solution you'd like**<br>
An endpoint to resize an image possibly accepting a body with the following structure.
```json
{
  "filename": "string",
  "width": "number",
  "height": "number",
}
```

**Describe alternatives you've considered**<br>
N/A

**Additional context**<br>
N/A

**Comment by juroberttyb** [comment]
Hi @kevinanielsen, I would like to work on this feature, cloud you assign me this issue?

**Comment by juroberttyb** [comment]
Also, please help review a small [PR](https://github.com/kevinanielsen/go-fast-cdn/pull/61) here, I would like to help improve other code in future PRs.

**Comment by kevinanielsen** [comment]
@juroberttyb You've been assigned - let me know if you need help with anything :)

Sure, I'll take a look at it!

**Comment by juroberttyb** [comment]
Hi @kevinanielsen, I have created a [PR](https://github.com/kevinanielsen/go-fast-cdn/pull/72) that adds an image resize endpoint. Please consider helping me review the PR. Thanks.

**Comment by kevinanielsen** [comment]
This issue is now closed. Thanks again for the contribution! :)
