### ISSUE TITLE
[Feature] Add possibility for uploading multiple images/documents

### ISSUE THREAD

**Issue by kevinanielsen** [kevinanielsen/go-fast-cdn#59]
**Is your feature request related to a problem? Please describe.** <br>
Currently, if you want to upload multiple images, you have to upload one at a time.

**Describe the solution you'd like**<br>
Make the UI component upload accept multiple files, then add a function for looping over those files and uploading one at a time.

**Describe alternatives you've considered**<br>
N/A

**Additional context**<br>
N/A

**Comment by WallysFerreira** [comment]
Can I get assigned to this pls?

**Comment by kevinanielsen** [comment]
Sure, let me know if you need any help!
