### ISSUE TITLE
[Feature] Update project to use something like https://golang.cafe/blog/golang-functional-options-pattern.html to help with server configuration

### ISSUE THREAD

**Issue by raj3k** [kevinanielsen/go-fast-cdn#94]
**Is your feature request related to a problem? Please describe.** <br>
No

**Describe the solution you'd like**<br>
Refactor current server configuration. Currently there is small number of configurational parameters but when this number will raise, using f.e. Options Pattern could be beneficial.

**Describe alternatives you've considered**<br>
N/a

**Additional context**<br>
https://golang.cafe/blog/golang-functional-options-pattern.html
or
https://github.com/eddycjy/go-gin-example/blob/master/main.go

**Comment by kevinanielsen** [comment]
I like this a lot - Would you like to work on this? @raj3k

**Comment by raj3k** [comment]
@kevinanielsen yes, i will work on that

**Comment by kevinanielsen** [comment]
Perfect - Assigning you now!

**Comment by josefmay** [comment]
Is this feature request being actively worked on? If not, I would like to work on it.

**Comment by kevinanielsen** [comment]
@josefmay I believe it is not, I can assign you to it now :)

**Comment by josefmay** [comment]
Still working on this at the moment.

**Comment by anveshthakur** [comment]
Hi @kevinanielsen, Is this issue still being worked on? Can I take it up?

**Comment by kevinanielsen** [comment]
> Hi @kevinanielsen, Is this issue still being worked on? Can I take it up?

No update from @josefmay - Anvesh you can work on this :)

**Comment by anveshthakur** [comment]
Hi @kevinanielsen, I've raised a PR for this issue which can be found here #147
